CC      ?= cc
CFLAGS  ?= -O2 -Wall -Wextra
ENGINE  ?= ../colibri/c

all: tracker maintainer liblumabri.so test_shim swarm_probe lumabri

# A checkout with Colibri's additive ABI gets the transparent Segment path
# from the ordinary `make`; older/release Colibri trees keep the exact legacy
# build.  The user still runs only `lumabri serve` and `lumabri chat`.
HAVE_COLIBRI_SEGMENT := $(and $(wildcard $(ENGINE)/segment_runtime.h),\
                                  $(wildcard $(ENGINE)/edge_runtime.h))
ifneq ($(HAVE_COLIBRI_SEGMENT),)
all: segment-direct
endif

# Compile every standalone repository-owned binary under the normal warning
# set and promote warnings to errors. Engine amalgamations are checked by
# their own upstream builds, because treating their warnings as Lumabri
# regressions would make this gate depend on whichever checkout ENGINE names.
check-warnings:
	$(MAKE) -B all test_relay_exec test_swarm_fed test_key_rotation \
		test_hedge test_local_fallback test_nat_adopt test_verify_failover test_rtt_refresh test_segment_v2 \
		test_segment_discovery test_swarm_detail test_relay_rate test_machine \
		test_meminfo test_compute_lease test_content_filter \
		test_scheduler test_run_gate \
		CFLAGS='$(CFLAGS) -Werror'

SECURE_DEPS = lumabri_secure.h lumabri_crypto.h
MACHINE_SRC = lumabri_machine.c
MACHINE_DEPS = lumabri_machine.h $(MACHINE_SRC)

lumabri: lumabri.c lumabri_proto.h lumabri_sign.h $(SECURE_DEPS) $(MACHINE_DEPS)
	$(CC) $(CFLAGS) -pthread lumabri.c $(MACHINE_SRC) -o $@

# ---- phase 2: peers execute experts ------------------------------------
# Both sides are built from the engine's own source so the expert math cannot
# drift between local and remote: expert_node.c includes olmoe.c, and the
# chatter is olmoe.c itself with -DLUMABRI_P2P.
P2P_CFLAGS = -O2 -fopenmp -Wall -I. -I$(ENGINE) \
             -Wno-unused-function -Wno-unused-parameter

phase2: expert_node olmoe_p2p
phase2-glm: expert_node_glm

# Which engines this colibri checkout actually has. deepseek.c in particular
# is GENERATED by colibri's tools/amalgamate_deepseek.py and is NOT in a fresh
# clone, so requiring it unconditionally breaks the build for everyone who has
# not run that generator — including anyone who only wants GLM. Everything is
# per engine anyway, so build what is there and say what was skipped.
# DeepSeek V4 ships two ways across colibri versions: current colibri has the
# unit-amalgamated deepseek_v4.c (compiled once per COLI_V4_UNIT_*, see
# Makefile.deepseek-v4.units); older trees had a single deepseek.c. Detect
# which, and count deepseek as present for either. Neither is in a stock clone
# of some other engine, so everything here is per engine: build what is there.
DS_SINGLE := $(wildcard $(ENGINE)/deepseek.c)
DS_MULTI  := $(wildcard $(ENGINE)/deepseek_v4.c)
HAVE_ENGINES := $(notdir $(basename $(wildcard $(ENGINE)/olmoe.c $(ENGINE)/colibri.c \
                 $(ENGINE)/inkling.c $(ENGINE)/kimi_k3.c $(ENGINE)/qwen36.c)))
HAVE_ENGINES += $(if $(DS_MULTI)$(DS_SINGLE),deepseek)

# Current colibri's kimi expert_apply grew two i8-activation params (zq,zsc);
# older trees took eight. The donor glue passes NULL,NULL (the float fallback,
# byte-identical) only when the source has them. Probe the exact signature tail
# so a stray zq elsewhere can't flip it. Empty on missing file or old layout.
K3_ZQ := $(shell grep -c 'const int8_t \*zq, const float \*zsc' $(ENGINE)/kimi_k3.c 2>/dev/null)
K3_ZQ_FLAG := $(if $(filter-out 0,$(K3_ZQ)),-DLMBE_K3_EXPERT_APPLY_ZQ,)
NODE_olmoe    = expert_node
NODE_colibri  = expert_node_glm
NODE_inkling  = expert_node_inkling
NODE_kimi_k3  = expert_node_kimi
NODE_deepseek = expert_node_deepseek
NODE_qwen36   = expert_node_qwen36

ENGINE_NODES    = $(foreach e,$(HAVE_ENGINES),$(NODE_$(e)))
# Both the expert node and the chatter build for either DeepSeek layout: the
# single file with a line patch, the multi-file source with an anchored one.
CHATTER_ENGINES := $(HAVE_ENGINES)
ENGINE_CHATTERS = $(foreach e,$(CHATTER_ENGINES),$(e)_p2p)
MISSING_ENGINES = $(filter-out $(HAVE_ENGINES),olmoe colibri inkling kimi_k3 deepseek qwen36)
MISSING_CHATTERS = $(filter-out $(CHATTER_ENGINES),$(HAVE_ENGINES))

# A strict distributed run must not mix engine sources or numeric build
# profiles. Hash contents only (not absolute paths), then inject the same ID
# into the chatter and expert-node build for that family. Compiler/ISA/OpenMP
# details are appended at runtime by lmb_build_profile().
ENGINE_PROFILE_DEPS := $(sort $(wildcard $(ENGINE)/*.h)) \
                       lumabri_client.h lumabri_proto.h lumabri_sign.h lumabri_sha.h \
                       $(SECURE_DEPS)
define engine_source_id
$(shell sha256sum $(ENGINE)/$(1).c $(ENGINE_PROFILE_DEPS) \
        expert_engines/$(2).h engine_patches/$(1)-p2p.diff 2>/dev/null | \
        awk '{print $$1}' | sha256sum | cut -c1-16)
endef
SRCID_olmoe   := $(call engine_source_id,olmoe,olmoe)
SRCID_colibri := $(call engine_source_id,colibri,colibri)
SRCID_inkling := $(call engine_source_id,inkling,inkling)
SRCID_kimi_k3 := $(call engine_source_id,kimi_k3,kimi_k3)
SRCID_qwen36  := $(call engine_source_id,qwen36,qwen36)
ifneq ($(DS_MULTI),)
SRCID_deepseek := $(call engine_source_id,deepseek_v4,deepseek)
else
SRCID_deepseek := $(call engine_source_id,deepseek,deepseek)
endif

PROFILE_olmoe   = -DLMBE_ENGINE_ID='"olmoe"'      -DLMBE_SOURCE_ID='"$(SRCID_olmoe)"'   -DLMBE_EXPECT_BITS=0
PROFILE_colibri = -DLMBE_ENGINE_ID='"colibri"'    -DLMBE_SOURCE_ID='"$(SRCID_colibri)"' -DLMBE_EXPECT_BITS=8
PROFILE_inkling = -DLMBE_ENGINE_ID='"inkling"'    -DLMBE_SOURCE_ID='"$(SRCID_inkling)"' -DLMBE_EXPECT_BITS=8
PROFILE_kimi_k3 = -DLMBE_ENGINE_ID='"kimi_k3"'    -DLMBE_SOURCE_ID='"$(SRCID_kimi_k3)"' -DLMBE_EXPECT_BITS=0
PROFILE_qwen36  = -DLMBE_ENGINE_ID='"qwen36"'     -DLMBE_SOURCE_ID='"$(SRCID_qwen36)"'  -DLMBE_EXPECT_BITS=0
PROFILE_deepseek= -DLMBE_ENGINE_ID='"deepseek_v4"' -DLMBE_SOURCE_ID='"$(SRCID_deepseek)"' -DLMBE_EXPECT_BITS=0

# The src= hash is baked into every PROFILE-carrying compile, but make tracks
# the mtimes of listed prerequisites, not the hash's VALUE. A rule whose
# prerequisites miss one hashed input (the chatters lack the engine headers;
# the deepseek bridge lacks the engine entirely) kept linking an object with
# a stale hash after a colibri update — three binaries, three epochs, three
# "incompatible manifest" rejections on one machine. A stamp per engine holds
# the value: rewritten only when the value changes, so depending on it makes
# a rule follow the hash without listing every hashed file.
build/srcid_%: FORCE
	@mkdir -p build
	@v='$(SRCID_$*)'; { [ -f $@ ] && [ "$$(cat $@)" = "$$v" ]; } || printf '%s\n' "$$v" > $@
FORCE:

# every engine's peer in one go — the ones this checkout has
engines: $(ENGINE_NODES)
	@$(if $(MISSING_ENGINES),echo "  skipped (no engine source in $(ENGINE)): $(MISSING_ENGINES)",:)
	@$(if $(MISSING_CHATTERS),echo "  chatter not yet ported to this colibri layout: $(MISSING_CHATTERS) (the expert node builds; the chat-side patch is pending)",:)

# everything phase 2 needs, both sides
phase2-all: engines chatters

# One expert-node binary per engine. The body is the same file; everything
# engine-shaped lives in expert_engines/<name>.h, which pulls in the engine's
# own source so remote and local run the same kernels on the same weights.
EXPERT_DEPS = expert_node.c lumabri_proto.h lumabri_sign.h $(SECURE_DEPS) $(MACHINE_DEPS)

expert_node: $(EXPERT_DEPS) expert_engines/olmoe.h $(ENGINE)/olmoe.c \
             engine_patches/olmoe-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_olmoe) expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread

expert_node_glm: $(EXPERT_DEPS) expert_engines/colibri.h $(ENGINE)/colibri.c \
                 engine_patches/colibri-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_colibri) -DLMBE_ENGINE_HEADER='"expert_engines/colibri.h"' \
	      expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread

expert_node_inkling: $(EXPERT_DEPS) expert_engines/inkling.h $(ENGINE)/inkling.c \
                     engine_patches/inkling-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_inkling) -DLMBE_ENGINE_HEADER='"expert_engines/inkling.h"' \
	      expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread

expert_node_kimi: $(EXPERT_DEPS) expert_engines/kimi_k3.h $(ENGINE)/kimi_k3.c \
                  engine_patches/kimi_k3-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_kimi_k3) $(K3_ZQ_FLAG) -DLMBE_ENGINE_HEADER='"expert_engines/kimi_k3.h"' \
	      expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread

# qwen36 (Qwen3.6): olmoe dialect, experts group-scaled and int4/int8, one row
# at a time. The CUDA VRAM tier is compiled out on CPU (qwen36_tier.h supplies
# inline stubs), so nothing beside qwen36.c needs linking.
expert_node_qwen36: $(EXPERT_DEPS) expert_engines/qwen36.h $(ENGINE)/qwen36.c \
                    engine_patches/qwen36-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_qwen36) -DLMBE_ENGINE_HEADER='"expert_engines/qwen36.h"' \
	      expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread

# DeepSeek V4 needs two extra things at build time.
#
# Its own -D set (upstream's expert-store sizing) has to match, or the store
# is laid out differently than the engine expects.
#
# And deepseek.c does `#undef main` halfway through — it renames a legacy
# entry point of its own — which kills the usual `#define main` trick every
# other glue relies on. So the CLI entry point is renamed textually into a
# build copy instead. One deterministic substitution, and if upstream ever
# changes that signature the copy still has a second main() and the compile
# says so rather than silently building the wrong program.
ifneq ($(DS_MULTI),)
# ---- current colibri: unit-amalgamated deepseek_v4.c --------------------
# deepseek_v4.c is compiled once per COLI_V4_UNIT_* into a separate object;
# Makefile.deepseek-v4.units lists the units that make the target binary. We
# build those, neutralise the CLI main()s (there are two, both in the stats
# unit), and link the objects with expert_node.c. The store-sizing -D set must
# match colibri's own build or the expert store lays out differently, so it is
# taken verbatim from Makefile.deepseek-v4.
DS_CFLAGS = -DCOLI_V4_MAX_PIN_SLOTS_PER_LAYER=16 -DCOLI_V4_PIN_RAMP_REQUESTS=24 \
            -DCOLI_V4_EXPERIMENTAL_DUAL_EXPERT_LOADER
DS_UNITS := $(shell awk '/^V4_TARGET_UNITS/{f=1} f{print} f&&!/\\$$/{exit}' \
              $(ENGINE)/Makefile.deepseek-v4.units 2>/dev/null | \
              grep -oE 'COLI_V4_UNIT_[A-Z0-9_]+')
DS_OBJS  := $(patsubst %,build/ds_%.o,$(DS_UNITS))
DS_UNIT_CFLAGS = -O2 -fopenmp -pthread -D_GNU_SOURCE -include pthread.h -I$(ENGINE) $(DS_CFLAGS)
DS_HDRS := $(wildcard $(ENGINE)/deepseek_v4*.h $(ENGINE)/deepseek_v4*.inc)

# Current colibri split the pluggable expert-store backend out of deepseek_v4.c
# into a standalone sibling TU that every V4 link now folds in
# (Makefile.deepseek-v4: V4_OBJS = target units + REGISTRY_OBJ). It is not a
# COLI_V4_UNIT_*, so deepseek_v4.c references it (coli_expert_store_backend_*)
# but our unit objects do not define it — link fails without it. Discover the
# source from colibri's own REGISTRY_OBJ so a rename follows us, and gate on the
# file existing so trees that predate the split link exactly as before. The one
# object is identical for node and chatter (no P2P, no ext header), so it is
# shared by both links.
DS_REGISTRY_OBJNAME := $(shell awk -F= '/^REGISTRY_OBJ[ \t]*=/{gsub(/[ \t]/,"",$$2);print $$2}' \
                         $(ENGINE)/Makefile.deepseek-v4 2>/dev/null)
DS_SIBLING_SRCS := $(foreach o,$(DS_REGISTRY_OBJNAME),$(wildcard $(ENGINE)/$(o:.o=.c)))
DS_SIBLING_HDRS := $(wildcard $(ENGINE)/expert_store*.h)
DS_SIBLING_OBJS := $(patsubst $(ENGINE)/%.c,build/dssib_%.o,$(DS_SIBLING_SRCS))

build/dssib_%.o: $(ENGINE)/%.c $(DS_HDRS) $(DS_SIBLING_HDRS)
	@mkdir -p build
	$(CC) $(DS_UNIT_CFLAGS) -c $< -o $@

build/deepseek_v4_noentry.c: $(ENGINE)/deepseek_v4.c
	@mkdir -p build
	@awk '/^int main\(int argc, char \*\*argv\) \{/{c++; sub(/^int main/,"int coli_v4_cli_unused_main_"c)} {print}' \
	     $< > $@
	@grep -q coli_v4_cli_unused_main $@ || \
	  { echo "deepseek_v4.c: no main() to neutralise — layout changed, update the rule"; exit 1; }

build/ds_%.o: build/deepseek_v4_noentry.c $(DS_HDRS)
	@mkdir -p build
	$(CC) $(DS_UNIT_CFLAGS) -D$* -c $< -o $@

expert_node_deepseek: $(EXPERT_DEPS) expert_engines/deepseek.h $(DS_OBJS) $(DS_SIBLING_OBJS) $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_deepseek) $(DS_CFLAGS) -DLMBE_DS_MULTIFILE -I$(ENGINE) \
	      -DLMBE_ENGINE_HEADER='"expert_engines/deepseek.h"' \
	      expert_node.c $(MACHINE_SRC) $(DS_OBJS) $(DS_SIBLING_OBJS) -o $@ -lm -lpthread

# The chatter: the same units WITH main (it is the CLI), patched at the three
# expert-apply sites to delegate routed experts to peers. The lumabri client
# state lives in one object (lumi_v4_bridge.o) so it is not duplicated per unit.
DS_P2P_OBJS := $(patsubst %,build/dsp2p_%.o,$(DS_UNITS))

build/deepseek_v4_p2p.c: $(ENGINE)/deepseek_v4.c engine_patches/deepseek_v4_p2p.py
	@mkdir -p build
	@python3 engine_patches/deepseek_v4_p2p.py $< $@

build/lumi_v4_bridge.o: lumi_v4_bridge.c $(ENGINE_P2P_DEPS) build/srcid_deepseek
	@mkdir -p build
	$(CC) -O2 -fopenmp -pthread -I. -Wno-unused-function $(PROFILE_deepseek) $(DS_CFLAGS) \
	      -c lumi_v4_bridge.c -o $@

build/dsp2p_%.o: build/deepseek_v4_p2p.c $(DS_HDRS) lumi_v4_ext.h
	@mkdir -p build
	$(CC) $(DS_UNIT_CFLAGS) -I. -include lumi_v4_ext.h -DLUMABRI_P2P -DLUMIBRI_P2P -D$* -c $< -o $@

deepseek_p2p: $(DS_P2P_OBJS) build/lumi_v4_bridge.o $(DS_SIBLING_OBJS)
	$(CC) -O2 -fopenmp $(DS_P2P_OBJS) build/lumi_v4_bridge.o $(DS_SIBLING_OBJS) -o $@ -lm -lpthread
else
# ---- older colibri: single generated deepseek.c -------------------------
# It undefines `main` halfway through, so the CLI entry is renamed textually
# into a build copy and the whole amalgamation is included by the glue.
DS_CFLAGS = -DCOLI_V4_MAX_PIN_SLOTS_PER_LAYER=16 -DCOLI_V4_PIN_RAMP_REQUESTS=24 \
            -DCOLI_V4_EXPERIMENTAL_BLOCK_OTHER_PROFILE \
            -DCOLI_V4_EXPERIMENTAL_DUAL_EXPERT_LOADER

build/deepseek_noentry.c: $(ENGINE)/deepseek.c
	@mkdir -p build
	@sed 's/^int main(int argc, char \*\*argv) {/int deepseek_cli_main_unused(int argc, char **argv) {/' \
	     $< > $@
	@grep -q deepseek_cli_main_unused $@ || \
	  { echo "deepseek.c: main() signature changed — update the rule"; exit 1; }

expert_node_deepseek: $(EXPERT_DEPS) expert_engines/deepseek.h build/deepseek_noentry.c \
                      engine_patches/deepseek-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_deepseek) $(DS_CFLAGS) -Ibuild \
	      -DLMBE_ENGINE_HEADER='"expert_engines/deepseek.h"' \
	      expert_node.c $(MACHINE_SRC) -o $@ -lm -lpthread
endif

# Regenerate the engine patches from a colibri checkout (never modifies it)
patches:
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE)

patches-check:
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --check

# ---- the chatter side: one patched engine binary per engine -------------
#
# `lumabri chat` prefers <engine>_p2p over <engine> in --engines-dir, and
# without one it runs the stock engine — which works, but phase 2 never
# engages and the chatter quietly downloads expert weights instead of asking
# peers to run them. So every engine needs its build here, not just olmoe.
#
# The engine is never modified: the patch is applied to a COPY under build/.
# A working copy that already has the patch applied is taken as-is, so an
# engine tree someone patched by hand still builds. Early OLMoE patches used
# `L.on` directly; normalize that old hook in the build copy so periodic
# discovery still runs while phase 2 is active.
#
# -DLUMIBRI_P2P: the patches predate the rename and test that macro; both
# spellings are defined so either vintage compiles.
build/%_p2p.c: $(ENGINE)/%.c engine_patches/make_patches.py engine_patches/%-p2p.diff Makefile
	@mkdir -p build
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one $*.c --out $@
	@sed -i 's/if (L\.on) {/if (lumi_layer_on(layer)) {/' $@

ENGINE_P2P_DEPS = lumabri_client.h lumibri_client.h lumabri_proto.h lumabri_sign.h \
                  $(SECURE_DEPS)

olmoe_p2p: build/olmoe_p2p.c $(ENGINE_P2P_DEPS) build/srcid_olmoe
	$(CC) $(P2P_CFLAGS) $(PROFILE_olmoe) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

colibri_p2p: build/colibri_p2p.c $(ENGINE_P2P_DEPS) build/srcid_colibri
	$(CC) $(P2P_CFLAGS) $(PROFILE_colibri) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

inkling_p2p: build/inkling_p2p.c $(ENGINE_P2P_DEPS) build/srcid_inkling
	$(CC) $(P2P_CFLAGS) $(PROFILE_inkling) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

qwen36_p2p: build/qwen36_p2p.c $(ENGINE_P2P_DEPS) build/srcid_qwen36
	$(CC) $(P2P_CFLAGS) $(PROFILE_qwen36) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

kimi_k3_p2p: build/kimi_k3_p2p.c $(ENGINE_P2P_DEPS) build/srcid_kimi_k3
	$(CC) $(P2P_CFLAGS) $(PROFILE_kimi_k3) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

# The single-file chatter rule; the multi-file one is defined near the node,
# above, so only one deepseek_p2p recipe exists for a given colibri layout.
ifeq ($(DS_MULTI),)
deepseek_p2p: build/deepseek_p2p.c $(ENGINE_P2P_DEPS) build/srcid_deepseek
	$(CC) $(P2P_CFLAGS) $(PROFILE_deepseek) $(DS_CFLAGS) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread
endif

# what a CHATTER needs; `engines` is what a compute DONOR needs
chatters: $(ENGINE_CHATTERS)

tiny_olmoe/config.json: make_tiny_olmoe.py
	python3 make_tiny_olmoe.py tiny_olmoe

fixture: tiny_olmoe/config.json

test-phase2: phase2 fixture
	bash ./phase2_test.sh

test-phase2-glm: phase2-glm
	bash ./phase2_glm_test.sh

test-phase2-inkling: expert_node_inkling
	bash ./phase2_inkling_test.sh

test-phase2-kimi: expert_node_kimi
	bash ./phase2_kimi_test.sh

# needs a real DeepSeek V4 model: MODEL=<dir> (no synthetic fixture, see the
# script's header for why)
test-phase2-deepseek: expert_node_deepseek
	bash ./phase2_deepseek_test.sh

test-phase2-qwen36: expert_node_qwen36
	bash ./phase2_qwen36_test.sh

# Every engine's byte-identity proof, one after the other. DeepSeek V4 has no
# synthetic fixture (see phase2_deepseek_test.sh), so it runs only when a real
# model is there — and says so when it is not, rather than quietly passing on
# four engines while claiming five.
test-engines: test-phase2 test-phase2-glm test-phase2-inkling test-phase2-kimi
	@if [ -f "$${MODEL:-$$HOME/deepseek_v4}/config.json" ]; then \
	    $(MAKE) --no-print-directory test-phase2-deepseek; \
	else \
	    echo; echo "── DeepSeek V4 SKIPPED: no model at $${MODEL:-$$HOME/deepseek_v4}"; \
	    echo "   it has no synthetic fixture — MODEL=<dir> make test-engines"; \
	fi

tracker: tracker.c lumabri_segment_discovery.c lumabri_segment_discovery.h \
		 lumabri_segment.c lumabri_segment.h lumabri_proto.h lumabri_sha.h \
		 lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread tracker.c lumabri_segment_discovery.c \
		lumabri_segment.c -o $@

maintainer: maintainer.c lumabri_content.h lumabri_proto.h lumabri_sha.h \
		lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread maintainer.c -o $@

# The shim interposes libc symbols, so it must not itself be interposable
# state: -fPIC shared object, resolved via RTLD_NEXT at load time.
liblumabri.so: lumashim.c lumabri_proto.h lumabri_sha.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -shared -fPIC -pthread lumashim.c -o $@ -ldl

test_shim: test_shim.c lumabri_content.h
	$(CC) $(CFLAGS) test_shim.c -o $@

test_relay_exec: test_relay_exec.c lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_relay_exec.c -o $@

test_key_rotation: test_key_rotation.c lumabri_sign.h
	$(CC) $(CFLAGS) -pthread test_key_rotation.c -o $@

test_hedge: test_hedge.c lumabri_client.h lumabri_proto.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread test_hedge.c -o $@

test_local_fallback: test_local_fallback.c lumabri_client.h lumabri_proto.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread test_local_fallback.c -o $@

test_rtt_refresh: test_rtt_refresh.c lumabri_client.h lumabri_proto.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread test_rtt_refresh.c -o $@

test_nat_adopt: test_nat_adopt.c lumabri_client.h lumabri_proto.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread test_nat_adopt.c -o $@

test_verify_failover: test_verify_failover.c lumabri_client.h lumabri_proto.h lumabri_sign.h
	$(CC) $(CFLAGS) -pthread test_verify_failover.c -o $@

test_segment_v2: test_segment_v2.c lumabri_segment.c lumabri_segment.h \
		 lumabri_proto.h lumabri_sha.h
	$(CC) $(CFLAGS) -pthread test_segment_v2.c lumabri_segment.c -o $@

test_segment_discovery: test_segment_discovery.c lumabri_segment_discovery.c \
		lumabri_segment_discovery.h lumabri_segment.c lumabri_segment.h \
		lumabri_proto.h lumabri_sign.h lumabri_sha.h
	$(CC) $(CFLAGS) -pthread test_segment_discovery.c \
		lumabri_segment_discovery.c lumabri_segment.c -o $@

test_swarm_detail: test_swarm_detail.c lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_swarm_detail.c -o $@

swarm_probe: swarm_probe.c lumabri_proto.h lumabri_sign.h $(SECURE_DEPS)
	$(CC) $(CFLAGS) -pthread swarm_probe.c -o $@

test_relay_rate: test_relay_rate.c lumabri_segment.c lumabri_segment.h \
		lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_relay_rate.c lumabri_segment.c -o $@

test_machine: test_machine.c $(MACHINE_DEPS) lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_machine.c $(MACHINE_SRC) -o $@

test_meminfo: test_meminfo.c $(MACHINE_DEPS) lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_meminfo.c $(MACHINE_SRC) -o $@

test_compute_lease: test_compute_lease.c $(MACHINE_DEPS) lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_compute_lease.c $(MACHINE_SRC) -o $@

test_content_filter: test_content_filter.c lumabri_content.h
	$(CC) $(CFLAGS) test_content_filter.c -o $@

test_scheduler: test_scheduler.c lumabri_scheduler.h
	$(CC) $(CFLAGS) test_scheduler.c -o $@

test_run_gate: test_run_gate.c lumabri_run_gate.c lumabri_run_gate.h
	$(CC) $(CFLAGS) -pthread test_run_gate.c lumabri_run_gate.c -o $@

test-machine-governor: lumabri tracker swarm_probe expert_node segment_node fixture test_machine
	ENGINE=$(ENGINE) bash ./machine_governor_test.sh

test-doctor: all
	bash ./doctor_test.sh

SANITIZE_FLAGS = -O1 -g -Wall -Wextra -fno-omit-frame-pointer -fsanitize=address,undefined
test-sanitize:
	mkdir -p build/sanitize
	$(CC) $(SANITIZE_FLAGS) -pthread test_segment_v2.c lumabri_segment.c -o build/sanitize/test_segment_v2
	$(CC) $(SANITIZE_FLAGS) -pthread test_segment_discovery.c lumabri_segment_discovery.c lumabri_segment.c -o build/sanitize/test_segment_discovery
	$(CC) $(SANITIZE_FLAGS) -pthread test_run_gate.c lumabri_run_gate.c -o build/sanitize/test_run_gate
	$(CC) $(SANITIZE_FLAGS) -pthread test_meminfo.c $(MACHINE_SRC) -o build/sanitize/test_meminfo
	$(CC) $(SANITIZE_FLAGS) -pthread test_compute_lease.c $(MACHINE_SRC) -o build/sanitize/test_compute_lease
	$(CC) $(SANITIZE_FLAGS) test_content_filter.c -o build/sanitize/test_content_filter
	$(CC) $(SANITIZE_FLAGS) test_scheduler.c -o build/sanitize/test_scheduler
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_segment_v2
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_segment_discovery
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_run_gate
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_meminfo
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_compute_lease
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_content_filter
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/sanitize/test_scheduler

test-thread-sanitize:
	mkdir -p build/sanitize
	$(CC) -O1 -g -Wall -Wextra -fno-omit-frame-pointer -fsanitize=thread \
		-pthread test_run_gate.c lumabri_run_gate.c -o build/sanitize/test_run_gate_tsan
	TSAN_OPTIONS=halt_on_error=1 build/sanitize/test_run_gate_tsan

production-gate:
	bash ./production_gate.sh --engine $(ENGINE)

# ---- Segment direct data plane (requires Colibri's additive Edge ABI) ---
# `all` includes this only when both additive headers are present. A Lumabri
# checkout pointed at an older/release Colibri therefore keeps building the
# legacy product unchanged, while a matching dev checkout gets native UX.
HYBRID_ENGINE_DIR = build/segment-hybrid-colibri
COLIBRI_SEGMENT_LIB = $(HYBRID_ENGINE_DIR)/build/segment/libcolibri_segment_edge.a
HYBRID_ROOT = $(abspath .)
SEGMENT_CFLAGS = $(CFLAGS) -I. -I$(ENGINE) -fopenmp
SEGMENT_COMMON = segment_colibri.h lumabri_segment.c lumabri_segment.h \
		lumabri_segment_discovery.c lumabri_segment_discovery.h \
		lumabri_proto.h lumabri_sign.h lumabri_sha.h $(SECURE_DEPS)

HYBRID_PATCH_INPUTS = engine_patches/make_patches.py \
	engine_patches/deepseek_v4_p2p.py $(wildcard engine_patches/*-p2p.diff) \
	lumabri_client.h lumibri_client.h lumi_v4_ext.h lumi_v4_bridge.c \
	lumabri_proto.h lumabri_sign.h lumabri_secure.h lumabri_crypto.h \
	lumabri_sha.h

$(HYBRID_ENGINE_DIR)/.prepared: $(HYBRID_PATCH_INPUTS) \
		$(ENGINE)/colibri.c $(ENGINE)/inkling.c $(ENGINE)/kimi_k3.c \
		$(ENGINE)/olmoe.c $(ENGINE)/qwen36.c $(ENGINE)/qwen38.c \
		$(ENGINE)/deepseek_v4.c
	rm -rf $(HYBRID_ENGINE_DIR)
	mkdir -p $(HYBRID_ENGINE_DIR)
	cp -a $(ENGINE)/. $(HYBRID_ENGINE_DIR)/
	rm -rf $(HYBRID_ENGINE_DIR)/build
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one colibri.c --out $(HYBRID_ENGINE_DIR)/colibri.c
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one inkling.c --out $(HYBRID_ENGINE_DIR)/inkling.c
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one kimi_k3.c --out $(HYBRID_ENGINE_DIR)/kimi_k3.c
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one olmoe.c --out $(HYBRID_ENGINE_DIR)/olmoe.c
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --apply-one qwen36.c --out $(HYBRID_ENGINE_DIR)/qwen36.c
	python3 engine_patches/deepseek_v4_p2p.py $(ENGINE)/deepseek_v4.c $(HYBRID_ENGINE_DIR)/deepseek_v4.c
	touch $@

build/segment_hybrid_bridge.o: lumi_v4_bridge.c $(HYBRID_PATCH_INPUTS)
	mkdir -p build
	$(CC) $(CFLAGS) -fopenmp -pthread -I. -I$(ENGINE) -c lumi_v4_bridge.c -o $@

$(COLIBRI_SEGMENT_LIB): $(HYBRID_ENGINE_DIR)/.prepared build/segment_hybrid_bridge.o
	env -u MAKEFLAGS $(MAKE) -C $(HYBRID_ENGINE_DIR) MAKEOVERRIDES= \
		CFLAGS='-O2 -fopenmp -pthread -I$(HYBRID_ROOT) -include $(HYBRID_ROOT)/lumi_v4_ext.h -DLUMABRI_P2P -DLUMIBRI_P2P' \
		segment-edge-library
	$(AR) rcs $@ build/segment_hybrid_bridge.o

segment_node: segment_node.c $(SEGMENT_COMMON) $(COLIBRI_SEGMENT_LIB) $(MACHINE_DEPS) \
		lumabri_run_gate.c lumabri_run_gate.h
	$(CC) $(SEGMENT_CFLAGS) -pthread segment_node.c lumabri_segment.c \
		lumabri_segment_discovery.c $(MACHINE_SRC) lumabri_run_gate.c \
		$(COLIBRI_SEGMENT_LIB) -o $@ -lm

segment_chat: segment_chat.c lumabri_sampling.c lumabri_sampling.h \
		$(SEGMENT_COMMON) $(COLIBRI_SEGMENT_LIB)
	$(CC) $(SEGMENT_CFLAGS) -pthread segment_chat.c lumabri_segment.c \
		lumabri_segment_discovery.c lumabri_sampling.c \
		$(COLIBRI_SEGMENT_LIB) -o $@ -lm

test_sampling: test_sampling.c lumabri_sampling.c lumabri_sampling.h
	$(CC) $(CFLAGS) test_sampling.c lumabri_sampling.c -o $@ -lm

.PHONY: segment-direct
segment-direct: segment_node segment_chat

test-segment-direct-real: tracker maintainer liblumabri.so lumabri \
		segment-direct test_sampling
	./test_sampling
	bash ./segment_direct_test.sh
	bash ./segment_relay_test.sh
	bash ./segment_failover_test.sh
	bash ./segment_native_test.sh

test-segment-relay-real: tracker segment-direct
	bash ./segment_relay_test.sh

test-segment-failover-real: tracker segment-direct
	bash ./segment_failover_test.sh

test-segment-priority-real: tracker segment-direct
	bash ./segment_priority_test.sh

test-relay-exec: tracker expert_node test_relay_exec fixture
	bash ./relay_exec_test.sh

test_swarm_fed: test_swarm_fed.c lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_swarm_fed.c -o $@

test-swarm-fed: tracker maintainer liblumabri.so expert_node test_swarm_fed fixture
	bash ./swarm_fed_exec_test.sh

test-assign-race: tracker
	bash ./assign_race_test.sh

test-partial-phase2: tracker phase2 fixture
	bash ./partial_phase2_test.sh

test-elastic: tracker expert_node fixture
	bash ./elastic_hold_test.sh

test-resident: tracker swarm_probe expert_node fixture
	bash ./resident_hold_test.sh

# Segment keeps attention/state local while a complete MoE layer is served by
# a strict-RAM Expert donor. The second run kills that donor and proves that
# the unchanged local Colibri kernel takes over without losing the session.
test-segment-hybrid: tracker swarm_probe expert_node segment_node segment_chat fixture
	ENGINE=$(ENGINE) bash ./segment_hybrid_test.sh

test-cas: tracker maintainer liblumabri.so test_shim
	bash ./cas_test.sh

test-key-rotation: test_key_rotation
	./test_key_rotation

test-hedge: test_hedge
	./test_hedge

test-segment-v2: test_segment_v2
	./test_segment_v2

test-segment-discovery: tracker test_segment_discovery
	bash ./segment_discovery_test.sh

test: all test_key_rotation test_hedge test_local_fallback test_nat_adopt test_verify_failover test_rtt_refresh test_segment_v2 \
		test_segment_discovery test_swarm_detail test_relay_rate test_machine \
		test_meminfo test_compute_lease test_content_filter \
		test_scheduler test_run_gate
	bash ./selftest.sh
	bash ./donate_test.sh
	bash ./signed_donor_test.sh
	bash ./hot_cache_integrity_test.sh
	bash ./role_test.sh
	bash ./serve_failfast_test.sh
	bash ./security_test.sh
	bash ./expert_input_test.sh
	bash ./prefetch_policy_test.sh
	bash ./cas_test.sh
	bash ./relay_exec_test.sh
	bash ./peer_identity_test.sh
	bash ./key_test.sh
	bash ./sign_test.sh
	bash ./crypto_test.sh
	bash ./secure_test.sh
	bash ./encrypted_transport_test.sh
	bash ./verify_failover_test.sh
	./test_key_rotation
	./test_hedge
	./test_local_fallback
	./test_nat_adopt
	bash ./rtt_refresh_test.sh
	./test_segment_v2
	./test_meminfo
	./test_compute_lease
	./test_content_filter
	./test_scheduler
	./test_run_gate
	python3 ./test_swarm_bench.py
	python3 ./test_production_check.py
	python3 ./test_swarm_soak.py
	bash ./production_gate_test.sh
	bash ./segment_discovery_test.sh
	bash ./swarm_detail_test.sh
	bash ./relay_rate_test.sh
	bash ./machine_governor_test.sh
	bash ./doctor_test.sh

# ---- deploy -------------------------------------------------------------
# make install                    → /usr/local (needs sudo)
# make install PREFIX=$$HOME/.local  → per-user, no root
# Every binary lands in PREFIX/bin (they find each other via /proc/self/exe)
# and the shim in PREFIX/lib/lumabri. Phase-2 binaries are installed when
# they have been built (make phase2 ENGINE=...).
PREFIX ?= /usr/local

install: all
	install -d $(DESTDIR)$(PREFIX)/bin $(DESTDIR)$(PREFIX)/lib/lumabri
	install -m 755 lumabri tracker maintainer swarm_probe $(DESTDIR)$(PREFIX)/bin/
	install -m 644 liblumabri.so $(DESTDIR)$(PREFIX)/lib/lumabri/
	@for b in expert_node expert_node_glm expert_node_inkling expert_node_kimi \
	         expert_node_deepseek expert_node_qwen36 \
	         olmoe_p2p colibri_p2p inkling_p2p kimi_k3_p2p deepseek_p2p qwen36_p2p \
	         segment_node segment_chat; do \
	    [ -f $$b ] && install -m 755 $$b $(DESTDIR)$(PREFIX)/bin/ || true; done
	@echo "installed under $(DESTDIR)$(PREFIX)"

clean:
	rm -f tracker maintainer liblumabri.so test_shim swarm_probe lumabri \
	      test_relay_exec test_swarm_fed test_key_rotation test_hedge \
	      test_local_fallback test_nat_adopt test_rtt_refresh \
	      test_verify_failover test_segment_v2 test_segment_discovery test_sampling \
	      test_swarm_detail test_relay_rate test_machine test_meminfo \
	      test_compute_lease test_content_filter test_scheduler test_run_gate \
	      test_segment_v2_tsan tracker_tsan \
	      segment_node segment_chat segment_node_asan segment_chat_asan \
	      segment_node_tsan segment_chat_tsan \
	      olmoe_p2p colibri_p2p inkling_p2p kimi_k3_p2p deepseek_p2p qwen36_p2p \
	      expert_node expert_node_glm expert_node_inkling expert_node_kimi \
	      expert_node_deepseek expert_node_qwen36
	rm -rf build

.PHONY: all check-warnings test clean install phase2 phase2-glm engines chatters phase2-all \
        fixture test-phase2 \
        test-phase2-glm test-phase2-inkling test-phase2-kimi \
        test-phase2-deepseek test-engines \
        patches patches-check test-relay-exec test-swarm-fed test-assign-race test-partial-phase2 test-elastic \
        test-cas test-key-rotation test-hedge test-segment-v2 \
        test-segment-discovery segment-direct test-segment-direct-real \
        test-segment-relay-real test-segment-failover-real test-segment-hybrid \
        test-machine-governor test-doctor test-sanitize test-thread-sanitize \
        production-gate
